base/urls.py
from django.urls import path
from . import views
from .views import logout_view
app_name="base"
urlpatterns = [
    path('home/', views.home, name="home"),
    path('posts/', views.posts, name="posts"),
    path('privacy_policy/', views.privacy, name="privacy"),
    path('post/', views.post, name="post"),
    path('term_of_use/', views.terms, name="terms"),
    path('profile/', views.profile, name="profile"),
    path('update_profile/', views.update_profile, name="update_profile"),
    path('login/', views.login_user, name="login"),
    path('logout/', logout_view, name='logout'),

]

profilator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.urls import reverse
from datetime import datetime, date


# Create your models here.
class Login(AbstractUser):
    name = models.CharField(max_length=200, null= True)
    email = models.EmailField(unique=True, null=True)

    def __str__(self):
        return str(self.name)

class Bio(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(null=True, blank=True, upload_to="images")
    description = models.TextField()
    author1 = models.CharField(max_length=255)
    author2 = models.CharField(max_length=255)
    author1_link_facebook = models.URLField(max_length=255)
    author2_link_linkedin = models.URLField(max_length=255)

    def __str__(self):
        return str(self.name)



    # def get_absolute_url(self):
    #     return reverse('home')

base/forms.py
from django import forms
from django.forms import ModelForm
from .models import Login, Bio


# create a venue form

class LoginForm(ModelForm):
    class Meta:
        model = Login
        fields = ('name', 'email')


        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter your name'}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Enter a valid email address'})

        }


class BioForm(ModelForm):
    class Meta:
        model = Bio
        fields = ('name','image','description','author1','author2','author1_link_facebook','author2_link_linkedin')


        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter your name'}),
            'image': forms.FileInput(attrs={'class':'form-control', 'placeholder':'Select a Photo'}),
            'description': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Describe your role'}),
            'author1': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter link'}) ,
            'author2': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter 2nd link'}),
            'author1_link_facebook': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter link'}),
            'author2_link_linkedin': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter 2nd link'})

        }

base/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import LoginForm, BioForm
from .models import Bio
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def home(request):
    items = Bio.objects.all()
    context = {
       "items":items,
    }
    
    return render(request, 'base/main.html', context )


def posts(request):
    return render(request, 'base/posts.html')

def privacy(request):
    return render(request, 'base/privacy.html')

def terms(request):
    return render(request, 'base/terms.html')


def post(request):
    return render(request, 'base/post.html')

def profile(request):
    try:
        bio_instance = Bio.objects.get()
    except Bio.DoesNotExist:
        bio_instance = None
    # form = BioForm()
    if request.method == "POST":
        form = BioForm(request.POST, instance=bio_instance)
        if form.is_valid():
            if bio_instance:
                bio_instance.delete
            form.save()
            return redirect('base:home')
    else:
        form = BioForm(instance=bio_instance)
    return render(request, 'base/profile.html', {'form':form})


def update_profile(request):
    return render(request, 'base/updateProfile.html')

from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib import messages

def login_user(request):
    if request.user.is_authenticated:
        return redirect("base:home")  # Assuming 'home' is the name of your home view
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("base:profile")  # Assuming 'home' is the name of your home view
        else:
            messages.error(request, "Invalid username or password")
    return render(request, "base/login.html")


def logout_view(request):
    logout(request)

    return redirect('base:login')

base/templates/base/home.html
<h1>home</h1>

base/templates/base/login.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="profilator/static/css/profilator.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .form-holder {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    min-height: 100vh;
}

.form-holder .form-content {
    position: relative;
    text-align: center;
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-align-items: center;
    align-items: center;
    padding: 60px;

    .password-input {
            padding: 10px;
            width: 100%;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box; /* Ensure padding and border are included in width */
        }

        /* Style for the placeholder text */
        .password-input::placeholder {
            color: #999; /* Light gray color */
        }
}
    </style>
    <title>Document</title>
</head>
<body>
    <div class="form-body">
        <div class="row">
            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                        <h3>LOGIN</h3>
                        <p>Fill in the data below.</p>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <label>Username:</label>
                            <input type="text" name="username" class="password-input" placeholder="username">

                            <label>Password:</label>
                            <input type="password" name="password" class="password-input" placeholder="password">
                                    
                            <input type="submit" value="LOGIN" class="btn btn-primary">

                            <!-- {{ form.as_p }} -->
                            
    
                            <div class="form-button mt-3">
                                
                                <!-- <button id="submit" type="submit" class="btn btn-primary">LOG IN</button> -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>




{% endblock content %}

base/templates/base/navbar.html
{% block content %}
<nav id="mainNav" class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark">
    <div class="container"><a class="navbar-brand" href="#page-top">Profilator</a><button class="navbar-toggler navbar-toggler-right" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
        <div id="navbarResponsive" class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto text-uppercase">
                <li class="nav-item"><a class="nav-link" href="{% url 'base:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'base:posts' %}">Post</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'base:logout' %}">Log out</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'base:login' %}">Log in</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="">Team</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'base:login' %}"><button class="btn btn-primary" type="button">Update Profile</button></a></li>
                
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

base/templates/base/posts.html
{% extends 'base/main.html' %}

{% block content %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>No Posts Available</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    /* Custom styles */
    body {
      padding-top: 50px; 
      text-align: center;
    }
    /* .container {
      max-width: 400px;
      padding-top: 20px; 
    } */
  </style>

</head>
<body class="text-center">

    <div class="container mt-5 ">
        <h2 class="mb-4">No posts available for now </h2>
    </div>

<!-- Bootstrap JS and dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>


{% endblock content %}

base/templates/base/privacy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy - Profilator</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
      padding-top: 50px; 
      text-align: center;
    }
    </style>
</head>
<body>

    <header>
        {% include 'base/navbar.html' %}
    </header>

    <div class="container mt-5">
        <h1>Privacy Policy</h1>
        <p>Your privacy is important to us. It is Profilator's policy to respect your privacy regarding any information we may collect from you across our website, <a href="http://www.profilator.com">http://www.profilator.com</a>, and other sites we own and operate.</p>
        
        <p>We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.</p>
        
        <p>We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.</p>
        
        <p>We don’t share any personally identifying information publicly or with third-parties, except when required to by law.</p>
        
        <p>Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.</p>
        
        <p>You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.</p>
        
        <p>Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.</p>
        
        <p>This policy is effective as of 10 June 2024.</p>
    </div>

    <footer class="bg-dark text-white text-center py-3">
        <p>&copy; 2024 Profilator. All Rights Reserved.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</body>
</html>

base/templates/base/profile.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="profilator/static/css/profilator.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .form-holder {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    min-height: 100vh;
}

.form-holder .form-content {
    position: relative;
    text-align: center;
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-align-items: center;
    align-items: center;
    padding: 60px;
}
    </style>
    <title>Document</title>
</head>
<body>
    <div class="form-body">
        <div class="row">
            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                        <h3>EDIT PROFILE</h3>
                        <p>Fill in the data below.</p>
                        <form action="" method="POST">
                            {% csrf_token %}

                            {{ form.as_p }}
                            
    
                            <div class="form-button mt-3">
                                <input type="submit" value="CREATE PROFILE" class="btn btn-primary">
                                <!-- <button id="submit" type="submit" class="btn btn-primary">CREATE PROFILE</button>  -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>




{% endblock content %}

base/templates/base/terms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Use - Profilator</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
      padding-top: 50px; 
      text-align: center;
    }
    </style>
</head>
<body>

    <header>
        {% include 'base/navbar.html' %}
    </header>

    <div class="container mt-5">
        <h1>Terms of Use</h1>
        <p>Please read these terms of use carefully before using our website.</p>
        
        <h3>Conditions of Use</h3>
        <p>We will provide our services to you, which are subject to the conditions stated below in this document. Every time you visit this website, use its services or make a purchase, you accept the following conditions. This is why we urge you to read them carefully.</p>
        
        <h3>Privacy Policy</h3>
        <p>Before you continue using our website, we advise you to read our privacy policy regarding our user data collection. It will help you better understand our practices.</p>
        
        <h3>Copyright</h3>
        <p>Content published on this website (digital downloads, images, texts, graphics, logos) is the property of Profilator and/or its content creators and protected by international copyright laws. The entire compilation of the content found on this website is the exclusive property of Profilator.</p>
        
        <h3>Communications</h3>
        <p>The entire communication with us is electronic. Every time you send us an email or visit our website, you are going to be communicating with us. You hereby consent to receive communications from us. If you subscribe to the news on our website, you are going to receive regular emails from us. We will continue to communicate with you by posting news and notices on our website and by sending you emails. You also agree that all notices, disclosures, agreements, and other communications we provide to you electronically meet the legal requirements that such communications be in writing.</p>
        
        <h3>Applicable Law</h3>
        <p>By visiting this website, you agree that the laws of the Federal Republic of Nigeria, without regard to principles of conflict laws, will govern these terms of service, or any dispute of any sort that might come between Profilator and you, or its business partners and associates.</p>
        
        <h3>Disputes</h3>
        <p>Any dispute related in any way to your visit to this website or to products you purchase from us shall be arbitrated by state or federal court [your location] and you consent to exclusive jurisdiction and venue of such courts.</p>
        
        <h3>Changes to These Terms of Use</h3>
        <p>We reserve the right, at our sole discretion, to modify or replace these terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
        
        <p>By continuing to access or use our website after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the website.</p>
    </div>

    <footer class="bg-dark text-white text-center py-3">
        <p>&copy; 2024 Profilator. All Rights Reserved.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</body>
</html>

base/templates/base/updateProfile.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="profilator/static/css/profilator.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .form-holder {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    min-height: 100vh;
}

.form-holder .form-content {
    position: relative;
    text-align: center;
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-align-items: center;
    align-items: center;
    padding: 60px;
}
    </style>
    <title>Document</title>
</head>
<body>
    <div class="form-body">
        <div class="row">
            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                        <h3>Register Today</h3>
                        <p>Fill in the data below.</p>
                        <form class="requires-validation" novalidate>
    
                            <div class="col-md-12">
                               <input class="form-control" type="text" name="name" placeholder="Full Name" required>
                               <div class="valid-feedback">Username field is valid!</div>
                               <div class="invalid-feedback">Username field cannot be blank!</div>
                            </div>
    
                            <div class="col-md-12">
                                <input class="form-control" type="email" name="email" placeholder="E-mail Address" required>
                                 <div class="valid-feedback">Email field is valid!</div>
                                 <div class="invalid-feedback">Email field cannot be blank!</div>
                            </div>
    
                           <div class="col-md-12">
                                <select class="form-select mt-3" required>
                                      <option selected disabled value="">Position</option>
                                      <option value="jweb">Junior Web Developer</option>
                                      <option value="sweb">Senior Web Developer</option>
                                      <option value="pmanager">Project Manager</option>
                               </select>
                                <div class="valid-feedback">You selected a position!</div>
                                <div class="invalid-feedback">Please select a position!</div>
                           </div>
    
    
                           <div class="col-md-12">
                              <input class="form-control" type="password" name="password" placeholder="Password" required>
                               <div class="valid-feedback">Password field is valid!</div>
                               <div class="invalid-feedback">Password field cannot be blank!</div>
                           </div>
    
    
                           <div class="col-md-12 mt-3">
                            <label class="mb-3 mr-1" for="gender">Gender: </label>
    
                            <input type="radio" class="btn-check" name="gender" id="male" autocomplete="off" required>
                            <label class="btn btn-sm btn-outline-secondary" for="male">Male</label>
    
                            <input type="radio" class="btn-check" name="gender" id="female" autocomplete="off" required>
                            <label class="btn btn-sm btn-outline-secondary" for="female">Female</label>
    
                            <input type="radio" class="btn-check" name="gender" id="secret" autocomplete="off" required>
                            <label class="btn btn-sm btn-outline-secondary" for="secret">Secret</label>
                               <div class="valid-feedback mv-up">You selected a gender!</div>
                                <div class="invalid-feedback mv-up">Please select a gender!</div>
                            </div>
    
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                          <label class="form-check-label">I confirm that all data are correct</label>
                         <div class="invalid-feedback">Please confirm that the entered data are all correct!</div>
                        </div>
                  
    
                            <div class="form-button mt-3">
                                <button id="submit" type="submit" class="btn btn-primary">CREATE PROFILE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>




{% endblock content %}